// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SwordActiveRisk_BlogVerification.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("SwordActiveRisk_BlogVerification", SourceFile="Features\\SwordActiveRisk_BlogVerification.feature", SourceLine=0)]
    public partial class SwordActiveRisk_BlogVerificationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SwordActiveRisk_BlogVerification.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SwordActiveRisk_BlogVerification", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 5
testRunner.Given("User is at \"blog\" page of SwordActiveRisk portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate(string blogByDate, string numberOfArticles, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate the correct number of blog posts are shown for each blog post by date", null, exampleTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 9
testRunner.When("the user is on the Active Risk Blog Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
testRunner.Then("the Blog posts By Date are displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 11
testRunner.When(string.Format("the user clicks on Blog post by date \'{0}\'", blogByDate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
testRunner.Then("the active risk blog opens in a new tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 13
testRunner.And("the list of articles are present in The Active Risk Blog", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
testRunner.And(string.Format("the Number of Blogs posted match the referenced numbers \'{0}\'", numberOfArticles), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
testRunner.And("the user is on Active Risk Blog homepage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, F" +
            "ebruary 2017", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_February2017()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("February 2017", "2", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, J" +
            "anuary 2017", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_January2017()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("January 2017", "5", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, D" +
            "ecember 2016", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_December2016()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("December 2016", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, N" +
            "ovember 2016", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_November2016()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("November 2016", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, O" +
            "ctober 2016", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_October2016()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("October 2016", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, S" +
            "eptember 2016", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_September2016()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("September 2016", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, A" +
            "ugust 2016", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_August2016()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("August 2016", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, J" +
            "uly 2016", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_July2016()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("July 2016", "3", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, J" +
            "une 2016", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_June2016()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("June 2016", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, M" +
            "arch 2016", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_March2016()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("March 2016", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, J" +
            "anuary 2016", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_January2016()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("January 2016", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, N" +
            "ovember 2015", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_November2015()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("November 2015", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, O" +
            "ctober 2015", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_October2015()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("October 2015", "2", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, S" +
            "eptember 2015", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_September2015()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("September 2015", "5", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, A" +
            "ugust 2015", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_August2015()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("August 2015", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, J" +
            "uly 2015", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_July2015()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("July 2015", "3", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, A" +
            "pril 2015", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_April2015()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("April 2015", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, M" +
            "arch 2015", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_March2015()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("March 2015", "3", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, F" +
            "ebruary 2015", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_February2015()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("February 2015", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, D" +
            "ecember 2014", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_December2014()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("December 2014", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, O" +
            "ctober 2014", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_October2014()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("October 2014", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, S" +
            "eptember 2014", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_September2014()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("September 2014", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, A" +
            "ugust 2014", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_August2014()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("August 2014", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, A" +
            "pril 2014", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_April2014()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("April 2014", "2", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, M" +
            "arch 2014", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_March2014()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("March 2014", "2", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, F" +
            "ebruary 2014", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_February2014()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("February 2014", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, A" +
            "ugust 2013", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_August2013()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("August 2013", "3", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, J" +
            "uly 2013", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_July2013()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("July 2013", "5", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, J" +
            "une 2013", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_June2013()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("June 2013", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, A" +
            "pril 2013", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_April2013()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("April 2013", "5", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, M" +
            "arch 2013", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_March2013()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("March 2013", "6", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, F" +
            "ebruary 2013", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_February2013()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("February 2013", "8", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, J" +
            "anuary 2013", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_January2013()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("January 2013", "4", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, D" +
            "ecember 2012", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_December2012()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("December 2012", "2", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, N" +
            "ovember 2012", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_November2012()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("November 2012", "2", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, O" +
            "ctober 2012", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_October2012()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("October 2012", "6", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, S" +
            "eptember 2012", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_September2012()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("September 2012", "6", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, A" +
            "ugust 2012", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_August2012()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("August 2012", "7", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, J" +
            "uly 2012", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_July2012()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("July 2012", "4", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, J" +
            "une 2012", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_June2012()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("June 2012", "2", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, M" +
            "ay 2012", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_May2012()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("May 2012", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, A" +
            "pril 2012", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_April2012()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("April 2012", "2", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, M" +
            "arch 2012", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_March2012()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("March 2012", "8", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, F" +
            "ebruary 2012", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_February2012()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("February 2012", "4", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, J" +
            "anuary 2012", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_January2012()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("January 2012", "6", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate the correct number of blog posts are shown for each blog post by date, D" +
            "ecember 2011", SourceLine=18)]
        public virtual void ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate_December2011()
        {
#line 7
this.ValidateTheCorrectNumberOfBlogPostsAreShownForEachBlogPostByDate("December 2011", "7", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
